BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Opponent` (
	`OpponentID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Attacks`	TEXT,
	`HitPoints`	INTEGER NOT NULL,
	`ArmorClass`	INTEGER NOT NULL,
	`Size`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Encounter` (
	`EncounterID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`EncounterName`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Enc_Opp` (
	`Enc_Opp_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`OpponentID`	INTEGER NOT NULL,
	`EncounterID`	INTEGER NOT NULL,
	FOREIGN KEY(`OpponentID`) REFERENCES `Opponent`(`OpponentID`),
	FOREIGN KEY(`EncounterID`) REFERENCES `Encounter`(`EncounterID`)
);
CREATE TABLE IF NOT EXISTS `DM` (
	`DM_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`DMName`	TEXT NOT NULL DEFAULT 'Default_User'
);
INSERT INTO `DM` VALUES (1,'Test');
CREATE TABLE IF NOT EXISTS `Campaign` (
	`CampName`	TEXT NOT NULL,
	`DM_ID`	INTEGER NOT NULL,
	`CampID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	CONSTRAINT `fk_DM` FOREIGN KEY(`DM_ID`) REFERENCES `DM`(`DM_ID`)
);
CREATE TABLE IF NOT EXISTS `Camp_Enc` (
	`Camp_Enc_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`CampID`	INTEGER NOT NULL,
	`EncounterID`	INTEGER NOT NULL,
	FOREIGN KEY(`CampID`) REFERENCES `Campaign`(`CampaignID`),
	FOREIGN KEY(`EncounterID`) REFERENCES `Encounter`(`EncounterID`)
);
COMMIT;
